version: '3.8'

services:
  # LocalStack for AWS services simulation
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs,s3,apigateway,lambda,iam
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
    volumes:
      - ./deployment/local:/docker-entrypoint-initaws.d
      - localstack-data:/tmp/localstack

  # ClickHouse for metrics storage
  clickhouse:
    image: clickhouse/clickhouse-server:latest
    ports:
      - "8123:8123"  # HTTP interface
      - "9000:9000"  # Native interface
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    environment:
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=metrics

  # Metabase for visualization
  metabase:
    image: metabase/metabase:latest
    ports:
      - "3000:3000"
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_PLUGINS_DIR=/plugins
      - MB_ENABLE_PLUGINS=true
    volumes:
      - metabase-data:/metabase-data
      - ./deployment/local/metabase/plugins:/plugins

  # API service for metrics ingestion
  api:
    build:
      context: .
      dockerfile: deployment/local/Dockerfile.api
    ports:
      - "8000:8000"
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - QUEUE_NAME=metrics-queue
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    depends_on:
      - localstack
    volumes:
      - ./src:/app/src
      - ./examples:/app/examples

  # Worker service for processing metrics
  worker:
    build:
      context: .
      dockerfile: deployment/local/Dockerfile.worker
    environment:
      - AWS_ENDPOINT_URL=http://localstack:4566
      - QUEUE_NAME=metrics-queue
      - CLICKHOUSE_HOST=clickhouse
      - CLICKHOUSE_PORT=9000
      - CLICKHOUSE_USER=default
      - CLICKHOUSE_PASSWORD=default
      - CLICKHOUSE_DB=metrics
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_REGION=us-east-1
    depends_on:
      - localstack
      - clickhouse
    volumes:
      - ./src:/app/src

volumes:
  localstack-data:
  clickhouse-data:
  metabase-data:
